import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#304d32",
        "on-tertiary-fixed": "#111f08",
        "outline-variant": "#c2c8bf",
        "on-primary-fixed": "#04210a",
        "surface-container": "#f0eee9",
        "inverse-surface": "#30312e",
        "surface-container-low": "#f5f3ee",
        "on-error": "#ffffff",
        "secondary-fixed": "#e2e2e2",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#aecfac",
        "on-primary-container": "#98b996",
        tertiary: "#233118",
        "on-secondary-container": "#616363",
        "tertiary-fixed-dim": "#bacca8",
        "inverse-primary": "#aecfac",
        "surface-dim": "#dbdad5",
        "on-tertiary-container": "#a4b693",
        "surface-container-highest": "#e4e2dd",
        outline: "#737970",
        "primary-container": "#2d4a2f",
        "surface-tint": "#476648",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe0e0",
        primary: "#17331a",
        "tertiary-container": "#38482d",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1c19",
        "surface-bright": "#fbf9f4",
        "on-error-container": "#93000a",
        background: "#fbf9f4",
        "inverse-on-surface": "#f2f1ec",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2dd",
        "tertiary-fixed": "#d6e9c3",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#454747",
        "on-background": "#1b1c19",
        "on-tertiary-fixed-variant": "#3c4b30",
        "on-secondary-fixed": "#1a1c1c",
        surface: "#fbf9f4",
        "surface-container-high": "#eae8e3",
        "primary-fixed": "#c9ecc6",
        "on-surface-variant": "#424841",
        "secondary-fixed-dim": "#c6c6c7",
        error: "#ba1a1a",
        secondary: "#5d5f5f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        unit: "8px",
        "container-max": "1280px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Libre Caslon Text"],
        "display-lg-mobile": ["Libre Caslon Text"],
        "display-lg": ["Libre Caslon Text"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Libre Caslon Text"],
        "label-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-lg-mobile": ["44px", { lineHeight: "1.15", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [forms, containerQueries],
};
